// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2NRiZexhjXUxurHdVORi414I8ChNXOgc',
    appId: '1:703462821377:android:872c831c77dd268d79ba00',
    messagingSenderId: '703462821377',
    projectId: 'whatsapp-backend-d7ebb',
    storageBucket: 'whatsapp-backend-d7ebb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS3GALOq1O6B4YXi5TWY3i54c8TQ6O_m4',
    appId: '1:703462821377:ios:fa7114634c1668c679ba00',
    messagingSenderId: '703462821377',
    projectId: 'whatsapp-backend-d7ebb',
    storageBucket: 'whatsapp-backend-d7ebb.appspot.com',
    androidClientId: '703462821377-jhdk5dl6rdd8eo3909irgcadp7klkmql.apps.googleusercontent.com',
    iosClientId: '703462821377-isnmes1dbpma6bbhq3pqsmjkl5c5rtdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
